name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  debug_info:
    name: Debug info
    runs-on: ubuntu-22.04
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20.15'
      - name: Install npm package
        run: "npm install --global json5"
      - name: Validate
        run: |
          EXIT_CODE=0
          for f in *.json5; do
            echo "Validating ${f}"
            json5 --validate ${f}
            if [[ "$?" != "0" ]]; then
              EXIT_CODE=1
            fi
          done
          exit ${EXIT_CODE}
      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict *.json5
